# Firebase App Hosting 빌드 설정
# web-ssr 백엔드용 빌드 시점 환경 변수 설정
#
# 참고: 이 파일은 apps/web 디렉토리에 위치해야 함 (rootDirectory가 apps/web이므로)

env:
  # App Hosting에서는 `/api/*` 경로가 403으로 막힐 수 있으므로
  # 관리자 API는 `/admin-api/*` 프록시 경로를 사용한다.
  - variable: NEXT_PUBLIC_ADMIN_USE_FUNCTIONS
    value: "true"
  # 미리보기 관련 환경 변수
  - variable: NEXT_PUBLIC_PREVIEW_SECRET
    value: "atsignal-preview"
  - variable: NEXT_PUBLIC_WEB_PREVIEW_ORIGIN
    value: "https://web-ssr--atsignal.asia-east1.hosted.app"
  - variable: NEXT_PUBLIC_DOCS_PREVIEW_ORIGIN
    value: "https://docs-ssr--atsignal.asia-east1.hosted.app"
